### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by cuongcx** [uwnlp/open_type#4]
Run command: python main.py onto -lstm_type single -goal onto  -enhanced_mention

Error:

.../model_utils.py:167: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weighted_keys = self.key_softmax(k).view(input_embed.size()[0], -1, 1)
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    _train(config)
  File "main.py", line 133, in _train
    total_loss += loss.data.cpu()[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by helloleejq** [comment]
total_loss += loss.data.cpu().item()

**Comment by helloleejq** [comment]
> Run command: python main.py onto -lstm_type single -goal onto -enhanced_mention
> 
> Error:
> 
> .../model_utils.py:167: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
> weighted_keys = self.key_softmax(k).view(input_embed.size()[0], -1, 1)
> Traceback (most recent call last):
> File "main.py", line 276, in 
> _train(config)
> File "main.py", line 133, in _train
> total_loss += loss.data.cpu()[0]
> IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

total_loss += loss.data.cpu().item()
